### ISSUE TITLE
How about the case when weak delegate dies earlier than strong proxy?

### ISSUE THREAD

**Issue by rabovik** [steipete/PSTDelegateProxy#1]
See corresponding [example](https://github.com/rabovik/PSTDelegateProxy/commit/a675580285e8e76dc810dff7e52881220ed20db5#L0R28) _(sorry the code is in AppDelegate but I do not have XCode 5 right now for adding a correct test to your project)_.
There is an uncaught exception `-[NSProxy doesNotRecognizeSelector:...]` in this case.

That is the reason why I tried to synchronize lifetime of proxy and delegate when wrote [similar lib](https://github.com/rabovik/FastElegantDelegation/blob/master/FEDelegation/ARC/FEDProxy.h). I use weak proxy in the class and add proxy as associated object to the delegate. In such approach there can't be a situation that proxy is alive but delegate dead.

**Comment by steipete** [comment]
That was a nasty one, thanks for reporting. Fixed in 6a2443a8cf675298b600c83f7ce60db89b303763

**Comment by rabovik** [comment]
Yeah, trick with signatures cache works.
But `class_copyProtocolList` does not include inherited protocols or protocols adopted by superclasses.

And another point. You build cache for **all** objects protocols, but on practice only one protocol for particular delegate is used for message forwarding. Maybe an initializer `initWithDelegate:protocol:` will be more useful?

**Comment by steipete** [comment]
I've added a fix and test case for inherited protocols in 64d2b32fae99f4a91ea195073f33ec77fd7c1a88. (and also check for superclasses).

Looks like i need to handle properties as well.

**Comment by steipete** [comment]
Ah, properties are already handled properly. Should work now for all cases. Thanks!

**Comment by rabovik** [comment]
I did not notice earlier but using single global cache for all proxy instances does not seem a good idea. Different classes may have different signatures for the same selector.

**Comment by steipete** [comment]
Thought about that, but that would be quite
bad practice (since this is also limited to protocols). I might split up the cache on a class-level, thid would fix that case.

**Comment by rabovik** [comment]
1) I disagree that it is a bad practice. Completely different protocols (for example from different authors) may have methods with different signatures and it should be considered as a usual situation, it is a part of the language, e.g.

``` objective-c
@protocol ABAnimationManager <NSObject>
-(CGFloat)manager:(ABAnimationManager *)manager heightForView:(UIView *)view;
@end

@protocol XZAnimationManager <NSObject>
-(NSUInteger)manager:(XZAnimationManager *)manager heightForView:(UIView *)view;
@end
```

No one should check the whole runtime for selectors collision while designing a delegate. 

2) Why brute force the whole class list? You may make some change to `PSPDF_DELEGATE_PROXY(type)` macro (i.e. `PSPDF_DELEGATE_PROXY(PRPTOCOL_NAME)`) and cache only signatures from that protocol (and incorporated protocols). Moreover, protocol name may be grabbed from `delegate` property.

3) The whole approach may be a lot simpler.

``` objective-c
@interface PSPDFResizableView
@property (nonatomic, weak) id <PSPDFResizableViewDelegate> delegate; // only one delegate in public interface
@end

@implementation PSPDFResizableView
fed_use_proxy_for_delegate // just one-line macro and that's all
-(void)someMethod{
    // if self.delegate (returning autoreleased proxy) is alive then real delegate is alive too
    _acceptedStartPoint = self.delegate ? [self.delegate selectionView:self shouldStartSelectionAtPoint:location] : YES;
}
@end
```
- one `delegate` property - no space for unintentional mess of `self.delegateProxy` with `self.delegate`
- no need to explicitly specify delegate type - protocol name is grabbed from property
- no fake signatures - signatures cache is built using protocol (with incorporated protocols)
- no unusual `[... defaultYES]` syntax and automatic support for default values of other types
- if you try to call required method that is not implemented in the delegate, you'll receive an exception (as it should be)

**Comment by rabovik** [comment]
Ha. I wrote something stupid. Of course this won't work:

``` objective-c
_acceptedStartPoint = self.delegate ? [self.delegate selectionView:self shouldStartSelectionAtPoint:location] : YES;
}
```

**Comment by steipete** [comment]
Check out the latest iteration. It's now a lot less code and the selector-collision is almost gone. Just need to split the cache into one dict per protocol.

**Comment by rabovik** [comment]
Yeah, I see. But still [crashes](https://github.com/rabovik/PSTDelegateProxy/blob/19d0c7183b7de26b37ea488ceec9b624798c1a31/PSTDelegateExample/PSTDelegateExample/PSTAppDelegate.m#L35), now when calling required method:

``` objective-c
@protocol PSTExampleDelegate <NSObject>
@required
- (void)exampleDelegateRequiredMethod;
@end

    PSTDelegateProxy *delegateProxy;
    @autoreleasepool {
        TestDelegate *delegate = [TestDelegate new];
        delegateProxy = [[PSTDelegateProxy alloc] initWithDelegate:delegate
                                              conformingToProtocol:@protocol(PSTExampleDelegate)];
    }
    [(id<PSTExampleDelegate>)delegateProxy exampleDelegateRequiredMethod]; // <- crash
```

Signatures for required methods should also be cached.

**Comment by steipete** [comment]
This is now covered by 9586c0ea85d572b76376853a16d080ed27bea233. Love your input here! 
This commit also fixes potential selector clashes, the cache is now split in two parts.
