### ISSUE TITLE
Return `list` command on empty input like SF console does

### ISSUE THREAD

**Issue by mablae** [steipete/PSTDelegateProxy#5]

**Comment by steipete** [comment]
Can you explain what you mean here?

**Comment by mablae** [comment]
Pressing just "Return" without entering anything should return the list command like sf2 does :-)

I just tested the demo, didn't look at code actually..

**Comment by steipete** [comment]
What is sf2?

**Comment by mablae** [comment]
Ohh, fuck... This is the totally wrong repo.. Just delete the issue.. Sorry for this..

I ment this project https://github.com/pylebecq/Console.js

I messed up with tabs, again, sorry
